# Generated by Django 3.2.5 on 2021-08-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': '荣誉', 'verbose_name_plural': '荣誉'},
        ),
    ]
